spring.application.name=PortfolioWebsite
# Conexão com o banco de dados
spring.datasource.url=jdbc:mysql://localhost:3306/db_portfolio
spring.datasource.username=root
spring.datasource.password=rOOt1.
# Configurações do Hibernate (para criar as tabelas sozinho)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect